yggdrasil:
  application:
    version: 2.0.0
  server:
    protocol:
      - "grpc"

  remote:
    protocol:
      grpc:

  registry: "polaris"

  interceptor:
    unaryServer: "logger,polaris_limit"
    streamServer: "logger"
    config:
      logger:
        printReqAndRes: true

#jaeger:
#  endpoint: "http://localhost:14268/api/traces"
#  sampler: 1

polaris:
  client:
    global:
      serverConnector:
        addresses:
          - 127.0.0.1:8091
      statReporter:
        enable: true
        chain:
          - prometheus
  registry:
    registerGovernor: true