yggdrasil:
  application:
    namespace: "default"
    version: 2.0.0
  server:
    protocol:
      - "grpc"

  remote:
    logger:
      level: "debug"

  registry: "polaris"

  interceptor:
    unaryServer: "logger,polaris_limit"
    streamServer: "logger"
    config:
      logger:
        printReqAndRes: true

#jaeger:
#  endpoint: "http://localhost:14268/api/traces"
#  sampler: 1

polaris:
  client:
    global:
      serverConnector:
        addresses:
          - 18.140.59.96:31591
      statReporter:
        enable: true
        chain:
          - prometheus
  registry:
    registerGovernor: true